package Enum;

public enum EInstruction {
    REQUIRE_DATA_TRAFFIC_PERIOD,
    REQUIRE_DATA_CURRENT_TRAFFIC_STATE,

    SEND_DATA_TRAFFIC_PERIOD,
    SEND_DATA_CURRENT_TRAFFIC_STATE,

    SWITCH_MODE,
}
